name: Run pytest on pgscatalog.calcapp

on:
  push:
    paths:
      - 'pgscatalog.calcapp/**.py'
  pull_request:
    paths:
      - 'pgscatalog.calcapp/**.py'

jobs:
  calcapp-pytest:
    uses: ./.github/workflows/pytest.yaml
    with:
      package-directory: "pgscatalog.calcapp"