name: Run pytest on pgscatalog.corelib

on:
  push:
    paths:
      - 'pgscatalog.corelib/**.py'
  pull_request:
    paths:
      - 'pgscatalog.corelib/**.py'

jobs:
  pytest-corelib:
    uses: ./.github/workflows/pytest.yaml
    with:
      package-directory: "pgscatalog.corelib"