name: Run pytest on pgscatalog.matchapp

on:
  push:
    paths:
      - 'pgscatalog.matchapp/**.py'
  pull_request:
    paths:
      - 'pgscatalog.matchapp/**.py'

jobs:
  matchapp-pytest:
    uses: ./.github/workflows/pytest.yaml
    with:
      package-directory: "pgscatalog.matchapp"